-- SQLite Schema for School Database Management System

CREATE TABLE IF NOT EXISTS Admins (
    AdminID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Role VARCHAR(50) NOT NULL DEFAULT 'admin'
);

CREATE TABLE IF NOT EXISTS Guardians (
    GuardianID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) NOT NULL,
    Relationship VARCHAR(100),
    Contact VARCHAR(50),
    Email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Teachers (
    TeacherID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) NOT NULL,
    Gender VARCHAR(10),
    Contact VARCHAR(50),
    Email VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS Students (
    StudentID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) NOT NULL,
    Gender VARCHAR(10),
    DateOfBirth DATE,
    Address TEXT,
    Contact VARCHAR(50),
    GuardianID INTEGER REFERENCES Guardians(GuardianID),
    AdmissionDate DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS Classes (
    ClassID INTEGER PRIMARY KEY AUTOINCREMENT,
    ClassName VARCHAR(100) NOT NULL UNIQUE,
    RoomNumber VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS Sections (
    SectionID INTEGER PRIMARY KEY AUTOINCREMENT,
    ClassID INTEGER NOT NULL REFERENCES Classes(ClassID),
    SectionName VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Subjects (
    SubjectID INTEGER PRIMARY KEY AUTOINCREMENT,
    SubjectName VARCHAR(100) NOT NULL,
    ClassID INTEGER NOT NULL REFERENCES Classes(ClassID)
);

CREATE TABLE IF NOT EXISTS Enrollments (
    EnrollmentID INTEGER PRIMARY KEY AUTOINCREMENT,
    StudentID INTEGER NOT NULL REFERENCES Students(StudentID),
    ClassID INTEGER NOT NULL REFERENCES Classes(ClassID),
    SectionID INTEGER NOT NULL REFERENCES Sections(SectionID),
    EnrollmentDate DATE DEFAULT CURRENT_DATE,
    AcademicYear VARCHAR(20),
    Status VARCHAR(20) DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS Attendance (
    AttendanceID INTEGER PRIMARY KEY AUTOINCREMENT,
    StudentID INTEGER NOT NULL REFERENCES Students(StudentID),
    Date DATE NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'Present'
);

CREATE TABLE IF NOT EXISTS Exams (
    ExamID INTEGER PRIMARY KEY AUTOINCREMENT,
    SubjectID INTEGER NOT NULL REFERENCES Subjects(SubjectID),
    ExamDate DATE,
    TotalMarks INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ExamResults (
    ResultID INTEGER PRIMARY KEY AUTOINCREMENT,
    StudentID INTEGER NOT NULL REFERENCES Students(StudentID),
    ExamID INTEGER NOT NULL REFERENCES Exams(ExamID),
    MarksObtained INTEGER
);

CREATE TABLE IF NOT EXISTS Fees (
    FeeID INTEGER PRIMARY KEY AUTOINCREMENT,
    StudentID INTEGER NOT NULL REFERENCES Students(StudentID),
    Amount DECIMAL(10,2) NOT NULL,
    DueDate DATE NOT NULL,
    PaidDate DATE,
    Status VARCHAR(20) DEFAULT 'Unpaid'
);

CREATE TABLE IF NOT EXISTS TeacherAssignments (
    AssignmentID INTEGER PRIMARY KEY AUTOINCREMENT,
    TeacherID INTEGER NOT NULL REFERENCES Teachers(TeacherID),
    ClassID INTEGER NOT NULL REFERENCES Classes(ClassID),
    SectionID INTEGER NOT NULL REFERENCES Sections(SectionID),
    SubjectID INTEGER NOT NULL REFERENCES Subjects(SubjectID)
);

CREATE TABLE IF NOT EXISTS TeacherSubjects (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TeacherID INTEGER NOT NULL REFERENCES Teachers(TeacherID),
    SubjectID INTEGER NOT NULL REFERENCES Subjects(SubjectID)
);

CREATE TABLE IF NOT EXISTS TeacherActivities (
    ActivityID INTEGER PRIMARY KEY AUTOINCREMENT,
    TeacherID INTEGER NOT NULL REFERENCES Teachers(TeacherID),
    ClassID INTEGER NOT NULL REFERENCES Classes(ClassID),
    SectionID INTEGER NOT NULL REFERENCES Sections(SectionID),
    ActivityDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ActivityType VARCHAR(100) NOT NULL
);

-- Insert default admin account if not exists
INSERT OR IGNORE INTO Admins (Username, PasswordHash, Role) VALUES ('admin@school.com', 'admin123', 'admin');
